### ISSUE TITLE
Team member information for Team website

### ISSUE THREAD

**Issue by ghost** [jlee2967/Eventile#1]
Please reply to this ticket with the following information for the team roster website:
name:
program:
year:
skills:
background:
hobbies:
other:

**Comment by kyle782** [comment]
Name: Jisoo Lee
Program: Honors & Specialization in Computer Science
Year: 3rd
Skills: Java, C/C++, Python, HTML5, XML, VBA, Assembly, Lisp
Background: Korean
Hobbies: Fishing, Gaming, Table Tennis
Other: I don't know :)

**Comment by kennygalang** [comment]
Name: Kenneth Galang
Program: Honours & Specialization in Computer Science
Year: 2
Skills: Python, Java, C, C++
Background: Filipino
Hobbies: Gaming/League, Working out, Beatboxing, netflix
Other: Nothing

**Comment by garygcchiu** [comment]
Name: Gary Chiu
Program: Honours & Specialization in Computer Science
Year: 3
Skills: Java, C, Python, Javascript
Background: Chinese
Hobbies: Basketball, gaming, Netflix
Other: kpop

**Comment by ghost** [comment]
name: Christopher Steward
program: Honours Specialization in Computer Science
year: 3rd in CS, 5th overall
skills: C, Java, python, C++, HTML, Javascript, CSS, Assembly, Ruby, Haskell
background: English, Danish
hobbies: Gaming, Programming, Listening to music
other:

**Comment by vsubasri** [comment]
Name: Valli Subasri
Program: Honours Bachelor of Science -- Computer Science & Medical Science 
Year: 5
Skills: Java, C, Javascript, HTML, CSS, Ruby
Background: Sri Lankan
Hobbies: Thrifting/fashion, painting, trying new foods/restaurants 
Other: ?

**Comment by FrankJZ** [comment]
name: Frank Jiao
program: Computer Science and Medical Science
year: 5
skills: Java, C, python, HTML
background: Chinese
hobbies: Sports, reading
other:n/a

**Comment by ConnorChato** [comment]
Name: Connor Chato
Program: Honours Specialization in Biology with Computer Sciences Minor
Year: 5
Skills: Java, C, Python, R, Perl
Background: Hungarian/Scottish
Hobbies: Listening to/Playing/Teaching Music, Wilderness Camping
Other: ?
